# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

# pool:
#   name: Default
#   demands:
#    - agent.name -equals DESKTOP-AGES7IT
pool: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: CopyFiles@2
  displayName: 'Move Build Files to Artifacts'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/API/bin/$(buildConfiguration)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'BuildArtifacts'

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Free Trial(e3f1c626-1da7-4d18-bec3-ea8498719e07)'
    AuthenticationType: 'server'
    ServerName: 'sqldb-devops-test.database.windows.net'
    DatabaseName: 'Test'
    SqlUsername: 'sqladmin'
    SqlPassword: 'XRzIovh02TiSHtM'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(Build.ArtifactStagingDirectory)/API.dacpac'
    IpDetectionMethod: 'AutoDetect'
# - task: SqlDacpacDeploymentOnMachineGroup@0
#   inputs:
#     TaskType: 'dacpac'
#     DacpacFile: '$(Build.ArtifactStagingDirectory)/API.dacpac'
#     TargetMethod: 'server'
#     ServerName: 'DESKTOP-AGES7IT'
#     DatabaseName: 'NewDB'
#     AuthScheme: 'sqlServerAuthentication'
#     SqlUsername: 'admin'
#     SqlPassword: 'password'
# - task: SqlDacpacDeploymentOnMachineGroup@0
#   inputs:
#     TaskType: 'dacpac'
#     DacpacFile: '$(Build.ArtifactStagingDirectory)/API.dacpac'
#     TargetMethod: 'connectionString'
#     ConnectionString: 'Server=DESKTOP-AGES7IT;Database=NewDB;User ID=admin;Password=password;TrustServerCertificate=True'
    